language: node_js
node_js:
  - "4.1"
before_install:
  - npm install -g typescript@2.0
script:
  - bash ./compile-browser.sh
after_success:
  - bash ./travis-deploy.sh
branches:
  only:
    - master
notifications:
  email: false
