export const MUTATION_CHANCE = 0.01;

export const MUTATION_RELATIVE_FRICTION_DIFF = 0.05;
export const MUTATION_BONE_FRICTION_CHANCE = 0.2;

export const MUTATION_RELATIVE_STRENGTH_DIFF = 0.05;
export const MUTATION_MUSCLE_STRENGTH_CHANCE = 0.2;

export const MUTATION_DELETE_NODE_CHANCE = 0.01;

export const MUTATION_ADD_NODE_CHANCE = 0.01;
export const MUTATION_CONNECTION_CHANCE = 0.33;