/* ================ Mutation ================ */
export const MUTATION_CHANCE = 0.01;

export const MUTATION_RELATIVE_FRICTION_DIFF = 0.15;
export const MUTATION_BONE_FRICTION_CHANCE = 0.2;

export const MUTATION_ELASTICITY_FRICTION_DIFF = 0.15;
export const MUTATION_ELASTICITY_FRICTION_CHANCE = 0.2;

export const MUTATION_RELATIVE_STRENGTH_DIFF = 0.15;
export const MUTATION_MUSCLE_STRENGTH_CHANCE = 0.2;
export const MUTATION_MUSCLE_MIN_LEN_CHANCE = 0.15;
export const MUTATION_MUSCLE_MAX_LEN_CHANGE = 0.15;
export const MUTATION_MUSCLE_REALTIVE_LEN_DIFF = 0.05;

export const MUTATION_DELETE_BONE_CHANCE = 0.05;

export const MUTATION_ADD_BONE_CHANCE = 0.1;
export const MUTATION_CONNECTION_CHANCE = 0.33;

export const MUTATION_CHANGE_BONE_POS_CHANCE = 0.1;
export const MUTATION_CHANGE_BONE_POS_MIN = -10;
export const MUTATION_CHANGE_BONE_POS_MAX = 10;

/* ================ Generator ================ */
export const GENERATOR_BONE_MIN_RADIUS = 30;
export const GENERATOR_BONE_MAX_RADIUS = 35;

export const GENERATOR_MUSCLE_MIN_LENGTH_DIST_FACTOR = 0.5;
export const GENERATOR_MUSCLE_MAX_LENGTH_DIST_FACTOR = 0.75;
export const GENERATOR_MUSCLE_MIN_LENGTH_CONST = 0;
export const GENERATOR_MUSCLE_MAX_LENGTH_CONST = 500;
export const GENERATOR_MUSCLE_MIN_RELATIVE_LENGTH_DIFF = 0.2;
export const GENERATOR_MUSCLE_MAX_RELATIVE_LENGTH_DIFF = 0.5;

export const GENERATOR_MUSCLE_MIN_STRENGTH = 30;
export const GENERATOR_MUSCLE_MAX_STRENGTH = 45;

export const GENERATOR_MUSCLE_MIN_INTERVAL = 1;
export const GENERATOR_MUSCLE_MAX_INTERVAL = 4;

export const GENERATOR_MUSCLE_MIN_EXPAND_FACTOR = 0.33;
export const GENERATOR_MUSCLE_MAX_EXPAND_FACTOR = 0.66;

export const GENERATOR_BONE_MIN_AMOUNT = 3;
export const GENERATOR_BONE_MAX_AMOUNT = 4;

/* ================ CreatureDiff ================ */
export const CREATUREDIFF_BONE_ELASTICITY_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_FRICTION_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_MASS_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_POS_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_RADIUS_DIFF_THRESHOLD = 0;

export const CREATUREDIFF_BONE_ELASTICITY_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_FRICTION_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_MASS_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_POS_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_BONE_RADIUS_AVG_DIFF_THRESHOLD = 0;

export const CREATUREDIFF_BONE_DIFF_POINTS = 0;

export const CREATUREDIFF_MUSCLE_EXP_FACTOR_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_INTERVAL_TIME_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_MAX_LEN_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_MIN_LEN_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_STR_DIFF_THRESHOLD = 0;

export const CREATUREDIFF_MUSCLE_EXP_FACTOR_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_INTERVAL_TIME_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_MAX_LEN_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_MIN_LEN_AVG_DIFF_THRESHOLD = 0;
export const CREATUREDIFF_MUSCLE_STR_AVG_DIFF_THRESHOLD = 0;

export const CREATUREDIFF_MUSCLE_BONES_DIFF_POINTS = 0;
export const CREATUREDIFF_MUSCLE_DIFF_POINTS = 0;

export const CREATUREDIFF_MULTIPLIER = 0;
export const CREATUREDIFF_THRESHOLD = 0;

/* ================ PHYSICS ================ */
export const ARE_BALLS_COLLIDABLE = true;
export const PHYSICS_GRAVITY = 981;
export const GROUND_ELASTICITY = 0.5;
export const GROUND_FRICTION = 0.5;
export const AIR_RESISTANCE = 0.5;

/* ================ POPULATION ================ */
export const POPULATION_SIZE = 200;
export const FRACTION_OF_BREEDED_POPULATION = 0.8;
export const ENABLE_MASS_DESTRUCTION = true;
export const MASS_DESTRUCTION_FACTOR = 0.99;
export const MASS_DESTRUCTION_INTERVAL = 50;


/* ================ SIMULATION ================ */
export const RUN_DURATION = 20;
export const SIMULATION_RESOLUTION = 30;
